### ISSUE TITLE
Better way to include cocos2dx

### ISSUE THREAD

**Issue by NatWeiss** [soomla/cocos2dx-store#126]
Hey guys. :) Found some issues with the latest Soomla projects on Android so I'm letting you know.

First issue is that including Soomla forces a build of cocos2dx, even if it was already included. In my latest builds I have been using RapidGame, which prebuilds cocos2dx into .a library files. Cocos2dx never has to be compiled twice! It's pretty awesome. However, this line in your Android.mk causes all of cocos2dx to be recompiled:

LOCAL_WHOLE_STATIC_LIBRARIES += cocos2dx_static

Since it triggers a recompile and cocos2dx was already linked statically, the build fails because of duplicate symbols.

I was able to get Soomla compiling without the above line. Just comment it and add a few include directories:

LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../bindings/manual \
        $(LOCAL_PATH)/../../../../cocos \
        $(LOCAL_PATH)/../../../../cocos/base \
        $(LOCAL_PATH)/../../../../cocos/platform/android \
        $(LOCAL_PATH)/../../../../external/chipmunk/include/chipmunk \
        $(LOCAL_PATH)/../../../../../external/spidermonkey/include/android

There might be a module that could be included which would provide all those include directories, but everything I tried wasn't working, that's why the manual inclusion of those paths.

**Comment by refaelos** [comment]
A lot changed since this suggestion. I think the integrations process is better now.

Closing for now. Open if relevant.
