### ISSUE TITLE
IabActivity is destroyed during purchase.

### ISSUE THREAD

**Issue by pablopda** [soomla/cocos2dx-store#145]
cocos2dx v 2.1.4, 
soomla cocos2dx-store branch for v2 .
commit of cocos2dx-store: ec30ed92d8b2e475135ca13ea320bdd5a5a20032

EDITED
I have "IabActivity is destroyed during purchase" error when: I call a few times buyIem (  CCStoreInventory::sharedStoreInventory()->buyItem ) and that purchases goes ok (on diferent items or the same). After a couple of purchases quickly enogh I get the "payment succeful" message and application crash with this log error

10-15 05:45:29.447: D/cocos2d-x debug info(27193): SOOMLA StoreInventory SOOMLA/COCOS2DX Calling buyItem with: item-silver-ring
10-15 05:45:29.56710-15 05:45:29.447: D/cocos2d-x debug info(27193): SOOMLA StoreInventory SOOMLA/COCOS2DX Calling buyItem with: item-silver-ring
10-15 05:45:29.567: D/cocos2d-x debug info(27193): SOOMLA StoreInfo Trying to fetch an item with itemId: item-silver-ring
10-15 05:45:29.567: D/cocos2d-x debug info(27193): SoomlaEventHandler >>> ItemPurchaseStarted
10-15 05:45:29.587: D/cocos2d-x debug info(27193): SOOMLA StoreInfo Trying to fetch an item with itemId: item-silver-ring
10-15 05:45:29.597: D/cocos2d-x debug info(27193): SoomlaEventHandler >>> MarketPurchaseStarted
: D/cocos2d-x debug info(27193): SOOMLA StoreInfo Trying to fetch an item with itemId: item-silver-ring
10-15 05:45:29.567: D/cocos2d-x debug info(27193): SoomlaEventHandler >>> ItemPurchaseStarted
10-15 05:45:29.587: D/cocos2d-x debug info(27193): SOOMLA StoreInfo Trying to fetch an item with itemId: item-silver-ring
10-15 05:45:29.597: D/cocos2d-x debug info(27193): SoomlaEventHandler >>> MarketPurchaseStarted
10-15 05:45:29.687: E/SOOMLA GooglePlayIabService(27193): IabActivity is destroyed during purchase.
10-15 05:45:29.687: E/SOOMLA SoomlaStore(27193): ERROR: IabPurchase failed: IabActivity is destroyed during purchase.
10-15 05:45:29.697: D/AndroidRuntime(27193): Shutting down VM
10-15 05:45:29.697: W/dalvikvm(27193): threadid=1: thread exiting with uncaught exception (group=0x420737c0)
10-15 05:45:29.697: W/GAV2(27193): Thread[main,5,main]: dispatch call queued.  Need to call GAServiceManager.getInstance().initialize().
10-15 05:45:29.697: D/cocos2d-x debug info(27193): SoomlaEventHandler >>> UnexpectedErrorInStore
10-15 05:45:29.707: E/AndroidRuntime(27193): FATAL EXCEPTION: main
10-15 05:45:29.707: E/AndroidRuntime(27193): java.lang.NullPointerException
10-15 05:45:29.707: E/AndroidRuntime(27193): 	at com.soomla.store.billing.google.GooglePlayIabService$OnIabPurchaseFinishedListener.onIabPurchaseFinished(GooglePlayIabService.java:383)
10-15 05:45:29.707: E/AndroidRuntime(27193): 	at com.soomla.store.billing.IabHelper$5.run(IabHelper.java:357)
10-15 05:45:29.707: E/AndroidRuntime(27193): 	at android.os.Handler.handleCallback(Handler.java:730)
10-15 05:45:29.707: E/AndroidRuntime(27193): 	at android.os.Handler.dispatchMessage(Handler.java:92)
10-15 05:45:29.707: E/AndroidRuntime(27193): 	at android.os.Looper.loop(Looper.java:137)
10-15 05:45:29.707: E/AndroidRuntime(27193): 	at android.app.ActivityThread.main(ActivityThread.java:5289)
10-15 05:45:29.707: E/AndroidRuntime(27193): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-15 05:45:29.707: E/AndroidRuntime(27193): 	at java.lang.reflect.Method.invoke(Method.java:525)
10-15 05:45:29.707: E/AndroidRuntime(27193): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
10-15 05:45:29.707: E/AndroidRuntime(27193): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
10-15 05:45:29.707: E/AndroidRuntime(27193): 	at dalvik.system.NativeStart.main(Native Method)

 Must I wait a few seconds between each call of buyItem ?

Also I saw this a couple of times:
10-15 15:44:45.577: W/ActivityManager(479): Activity pause timeout for ActivityRecord{4287a9d0 u0 com.lvklabs.PackageName/com.soomla.store.billing.google.GooglePlayIabService$IabActivity}

**Comment by refaelos** [comment]
This issue is outdated. Closing. Open if still relevant.
