### ISSUE TITLE
ObjectForKey cannot be nil (key: marketTitle)

### ISSUE THREAD

**Issue by siucloud** [soomla/cocos2dx-store#153]
I'm trying to use cocos2dx-store on cocos2dx 2.2.3.

I setup In-App Purchases in iTunes Connect and followed the example for setting up virtual goods and categories from the wiki but when I initialize the StoreController the app crashes with an exception, this is the debug information in the log:

2014-12-04 13:04:36.927 InfiniteCore[22373:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: marketTitle)'
*** First throw call stack:
(0x303c7e83 0x3a7286c7 0x30302ecb 0x2b3d79 0x2931d5 0x30389e71 0x302fdab1 0x30ce3ec5 0x2c0b63 0x2c4c85 0x32ae2137 0x3ac0d0c3 0x3ac0d0af 0x3ac0f9a9 0x303925b1 0x30390e7d 0x302fb471 0x302fb253 0x3502f2eb 0x32bb0845 0x19a1a7 0x3ac21ab7)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

I'm testing the app on an iPhone 5s with iOS 7.

**Comment by MDKG** [comment]
Hi guys,

I had the same issue.  I don't know if this will help, but I fixed it by messing around with the in-app purchases on iTunes Connect.  The App Review team had rejected them, and we needed to modify the item descriptions and resubmit them.

**Comment by frankiefanstar** [comment]
Hi guys,
  When your app was rejected by App Review Team ,the status of your in-app-purchase item was "Rejected" and "Need Developer Action".At this situation,the app with soomla will crash with above errors when you enter the app.Once you have modified your in-app-purchase item title or description and the status of this items are changed to "Waiting for Review".The app work again.I think the Developer team of soomla should fix this bug when the in-app-purchase item was rejected.

**Comment by vedi** [comment]
@frankiefanstar, thank you for the hint! It very helps.

**Comment by sluzky** [comment]
@siucloud @frankiefanstar @konopka @MDKG this is fixed in v4.3.1
