### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by msaad99** [soomla/cocos2dx-store#157]
Hey there I'm getting this error when I compile after I changed the deployment target of cocos2dx-store and cocos2dx-core to ios 8.1

Undefined symbols for architecture i386:
  "cocos2d::CCDictionary::objectForKey(std::string const&)", referenced from:
      soomla::CCMarketItem::initWithDictionary(cocos2d::CCDictionary*) in libCocos2dXStore.a(CCMarketItem.o)

and 12 similiar errors. Whats the fix?

**Comment by sluzky** [comment]
What version of Cocos2d-x are you working with?

**Comment by msaad99** [comment]
Cocos2d-x 2.2.5. And yes I have added the right versions and everything.

**Comment by sluzky** [comment]
@msaad99 in general I don't think cocos2d-x v2 supports i386, as you can see the error you are receiving is from Cocos2d-x itself, and not from SOOMLA.
What target device are you compiling for?

**Comment by msaad99** [comment]
I'm compiling for the iphone 6 simulator. How do I remove the i386 architecture then. Its not added in my valid architecture in build settings. Thats set to the standard architecture (armv7, arm64)

**Comment by sluzky** [comment]
@msaad99 you cannot compile for the iPhone 6 simulator with Cocos2-x v2, you should select a non-x64/i386 target, like iPhone 4s or 5.

**Comment by msaad99** [comment]
So the app will not work on the actual iphone 6 devices either?

**Comment by sluzky** [comment]
@msaad99 to the best of my knowledge Cocos2d-x v2 only supports 32bit devices, so the answer is no.
I suggest you upgrade to Cocos2d-x v3.

**Comment by sluzky** [comment]
@msaad99 can I close this issue?
