### ISSUE TITLE
Android app crashes during IABHelper Setup.

### ISSUE THREAD

**Issue by MDKG** [soomla/cocos2dx-store#158]
Hello there.  I've been having trouble running my app on Android.  Here's my log.  So far, all I know is that the app crashes almost immediately.  Any help would be appreciated.  Here's my log:

01-12 15:20:59.514: E/Trace(700): error opening trace file: No such file or directory (2)
01-12 15:20:59.794: D/dalvikvm(700): Trying to load lib /data/data/com.VerticalDepth.StringIt/lib/libcocos2dcpp.so 0x4149a608
01-12 15:20:59.854: D/dalvikvm(700): Added shared lib /data/data/com.VerticalDepth.StringIt/lib/libcocos2dcpp.so 0x4149a608
01-12 15:20:59.864: D/JniHelper(700): JniHelper::setJavaVM(0x2a008e78), pthread_self() = 1073870640
01-12 15:21:00.213: D/Cocos2dxActivity(700): model=sdk
01-12 15:21:00.225: D/Cocos2dxActivity(700): product=sdk
01-12 15:21:00.225: D/Cocos2dxActivity(700): isEmulator=true
01-12 15:21:00.404: D/libEGL(700): loaded /system/lib/egl/libEGL_emulation.so
01-12 15:21:00.404: D/(700): HostConnection::get() New Host Connection established 0x2a0f8ac0, tid 700
01-12 15:21:00.454: D/libEGL(700): loaded /system/lib/egl/libGLESv1_CM_emulation.so
01-12 15:21:00.454: D/libEGL(700): loaded /system/lib/egl/libGLESv2_emulation.so
01-12 15:21:00.514: W/EGL_emulation(700): eglSurfaceAttrib not implemented
01-12 15:21:00.534: D/OpenGLRenderer(700): Enabling debug mode 0
01-12 15:21:00.604: D/(700): HostConnection::get() New Host Connection established 0x2a130640, tid 725
01-12 15:21:01.285: D/main(700): cocos_android_app_init
01-12 15:21:01.304: D/NdkGlue(700): retParamsJson: {}
01-12 15:21:01.324: D/NdkGlue(700): retParamsJson: {}
01-12 15:21:01.414: D/dalvikvm(700): GC_CONCURRENT freed 193K, 3% free 11009K/11271K, paused 38ms+30ms, total 120ms
01-12 15:21:01.424: D/NdkGlue(700): retParamsJson: {}
01-12 15:21:01.424: D/SOOMLA(700): initialize is called from java!
01-12 15:21:01.434: D/SOOMLA SoomlaStore(700): SoomlaStore Initializing ...
01-12 15:21:01.434: D/SOOMLA SoomlaStore(700): Searching for the attached IAB Service.
01-12 15:21:01.434: D/SOOMLA SoomlaStore(700): Trying to find google.GooglePlayIabService
01-12 15:21:01.434: D/SOOMLA SoomlaStore(700): IAB Service found. Initializing it.
01-12 15:21:01.444: D/SOOMLA StoreInfo(700): checking metadata version ...
01-12 15:21:01.474: D/SOOMLA StoreInfo(700): checking metadata version ...
01-12 15:21:01.474: D/SOOMLA KeyValueStorage(700): trying to fetch a value for key: meta.storeinfo
01-12 15:21:01.894: D/SOOMLA KeyValueStorage(700): the fetched value is {"goods":{"goodUpgrades":[],"goodPacks":[],"lifetime":[{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":0,"price":1.99,"marketTitle":"","androidId":"no_ads","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"className":"LifetimeVG","itemId":"no_ads","description":"Tired of ads?  This'll make them go away!","name":"No Ads"},{"purchasableItem":{"pvi_amount":2100,"pvi_itemId":"currency_chocolate_coin","purchaseType":"virtualItem"},"className":"LifetimeVG","itemId":"halloween_theme","description":"Halloween Theme","name":"Halloween Theme"},{"purchasableItem":{"pvi_amount":2100,"pvi_itemId":"currency_chocolate_coin","purchaseType":"virtualItem"},"className":"LifetimeVG","itemId":"christmas_theme","description":"Christmas Theme","name":"Christmas Theme"}],"equippable":[],"singleUse":[]},"currencyPacks":[{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":0.5,"marketTitle":"","androidId":"pouch_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":500,"className":"VirtualCurrencyPack","itemId":"pouch_of_coins","description":"This pouch of coins holds 500!","name":"Pouch of coins"},{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":0.99,"marketTitle":"","androidId":"box_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":1200,"className":"VirtualCurrencyPack","itemId":"box_of_coins","description":"This box of coins holds 1200!","name":"Box of coins"},{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":1.99,"marketTitle":"","androidId":"tin_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":2600,"className":"VirtualCurrencyPack","itemId":"tin_of_coins","description":"This tin of coins holds 2600!","name":"Tin of coins"},{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":2.99,"marketTitle":"","androidId":"chest_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":5400,"className":"VirtualCurrencyPack","itemId":"chest_of_coins","description":"This chest of coins holds 5400!","name":"Chest of coins"}],"currencies":[{"itemId":"currency_chocolate_coin","className":"VirtualCurrency","description":"","name":"Chocolate Coins"}],"categories":[]}
01-12 15:21:01.894: D/SOOMLA StoreInfo(700): the metadata-economy json (from DB) is {"goods":{"goodUpgrades":[],"goodPacks":[],"lifetime":[{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":0,"price":1.99,"marketTitle":"","androidId":"no_ads","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"className":"LifetimeVG","itemId":"no_ads","description":"Tired of ads?  This'll make them go away!","name":"No Ads"},{"purchasableItem":{"pvi_amount":2100,"pvi_itemId":"currency_chocolate_coin","purchaseType":"virtualItem"},"className":"LifetimeVG","itemId":"halloween_theme","description":"Halloween Theme","name":"Halloween Theme"},{"purchasableItem":{"pvi_amount":2100,"pvi_itemId":"currency_chocolate_coin","purchaseType":"virtualItem"},"className":"LifetimeVG","itemId":"christmas_theme","description":"Christmas Theme","name":"Christmas Theme"}],"equippable":[],"singleUse":[]},"currencyPacks":[{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":0.5,"marketTitle":"","androidId":"pouch_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":500,"className":"VirtualCurrencyPack","itemId":"pouch_of_coins","description":"This pouch of coins holds 500!","name":"Pouch of coins"},{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":0.99,"marketTitle":"","androidId":"box_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":1200,"className":"VirtualCurrencyPack","itemId":"box_of_coins","description":"This box of coins holds 1200!","name":"Box of coins"},{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":1.99,"marketTitle":"","androidId":"tin_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":2600,"className":"VirtualCurrencyPack","itemId":"tin_of_coins","description":"This tin of coins holds 2600!","name":"Tin of coins"},{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":2.99,"marketTitle":"","androidId":"chest_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":5400,"className":"VirtualCurrencyPack","itemId":"chest_of_coins","description":"This chest of coins holds 5400!","name":"Chest of coins"}],"currencies":[{"itemId":"currency_chocolate_coin","className":"VirtualCurrency","description":"","name":"Chocolate Coins"}],"categories":[]}
01-12 15:21:01.924: D/SOOMLA StoreInfo(700): checking metadata version ...
01-12 15:21:01.924: D/SOOMLA KeyValueStorage(700): trying to fetch a value for key: meta.storeinfo
01-12 15:21:01.974: I/dalvikvm(700): Total arena pages for JIT: 11
01-12 15:21:01.974: I/dalvikvm(700): Total arena pages for JIT: 12
01-12 15:21:01.983: D/SOOMLA KeyValueStorage(700): the fetched value is {"goods":{"goodUpgrades":[],"goodPacks":[],"lifetime":[{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":0,"price":1.99,"marketTitle":"","androidId":"no_ads","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"className":"LifetimeVG","itemId":"no_ads","description":"Tired of ads?  This'll make them go away!","name":"No Ads"},{"purchasableItem":{"pvi_amount":2100,"pvi_itemId":"currency_chocolate_coin","purchaseType":"virtualItem"},"className":"LifetimeVG","itemId":"halloween_theme","description":"Halloween Theme","name":"Halloween Theme"},{"purchasableItem":{"pvi_amount":2100,"pvi_itemId":"currency_chocolate_coin","purchaseType":"virtualItem"},"className":"LifetimeVG","itemId":"christmas_theme","description":"Christmas Theme","name":"Christmas Theme"}],"equippable":[],"singleUse":[]},"currencyPacks":[{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":0.5,"marketTitle":"","androidId":"pouch_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":500,"className":"VirtualCurrencyPack","itemId":"pouch_of_coins","description":"This pouch of coins holds 500!","name":"Pouch of coins"},{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":0.99,"marketTitle":"","androidId":"box_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":1200,"className":"VirtualCurrencyPack","itemId":"box_of_coins","description":"This box of coins holds 1200!","name":"Box of coins"},{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":1.99,"marketTitle":"","androidId":"tin_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":2600,"className":"VirtualCurrencyPack","itemId":"tin_of_coins","description":"This tin of coins holds 2600!","name":"Tin of coins"},{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":2.99,"marketTitle":"","androidId":"chest_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":5400,"className":"VirtualCurrencyPack","itemId":"chest_of_coins","description":"This chest of coins holds 5400!","name":"Chest of coins"}],"currencies":[{"itemId":"currency_chocolate_coin","className":"VirtualCurrency","description":"","name":"Chocolate Coins"}],"categories":[]}
01-12 15:21:01.983: D/SOOMLA StoreInfo(700): the metadata-economy json (from DB) is {"goods":{"goodUpgrades":[],"goodPacks":[],"lifetime":[{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":0,"price":1.99,"marketTitle":"","androidId":"no_ads","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"className":"LifetimeVG","itemId":"no_ads","description":"Tired of ads?  This'll make them go away!","name":"No Ads"},{"purchasableItem":{"pvi_amount":2100,"pvi_itemId":"currency_chocolate_coin","purchaseType":"virtualItem"},"className":"LifetimeVG","itemId":"halloween_theme","description":"Halloween Theme","name":"Halloween Theme"},{"purchasableItem":{"pvi_amount":2100,"pvi_itemId":"currency_chocolate_coin","purchaseType":"virtualItem"},"className":"LifetimeVG","itemId":"christmas_theme","description":"Christmas Theme","name":"Christmas Theme"}],"equippable":[],"singleUse":[]},"currencyPacks":[{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":0.5,"marketTitle":"","androidId":"pouch_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":500,"className":"VirtualCurrencyPack","itemId":"pouch_of_coins","description":"This pouch of coins holds 500!","name":"Pouch of coins"},{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":0.99,"marketTitle":"","androidId":"box_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":1200,"className":"VirtualCurrencyPack","itemId":"box_of_coins","description":"This box of coins holds 1200!","name":"Box of coins"},{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":1.99,"marketTitle":"","androidId":"tin_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":2600,"className":"VirtualCurrencyPack","itemId":"tin_of_coins","description":"This tin of coins holds 2600!","name":"Tin of coins"},{"purchasableItem":{"marketItem":{"marketPriceMicros":0,"marketPrice":"","consumable":1,"price":2.99,"marketTitle":"","androidId":"chest_of_coins","marketCurrencyCode":"","className":"MarketItem","marketDesc":""},"purchaseType":"market"},"currency_itemId":"currency_chocolate_coin","currency_amount":5400,"className":"VirtualCurrencyPack","itemId":"chest_of_coins","description":"This chest of coins holds 5400!","name":"Chest of coins"}],"currencies":[{"itemId":"currency_chocolate_coin","className":"VirtualCurrency","description":"","name":"Chocolate Coins"}],"categories":[]}
01-12 15:21:01.994: I/dalvikvm(700): Total arena pages for JIT: 13
01-12 15:21:01.994: I/dalvikvm(700): Total arena pages for JIT: 14
01-12 15:21:01.994: I/dalvikvm(700): Total arena pages for JIT: 15
01-12 15:21:01.994: I/dalvikvm(700): Total arena pages for JIT: 16
01-12 15:21:02.003: I/dalvikvm(700): Total arena pages for JIT: 17
01-12 15:21:02.013: D/SOOMLA GooglePlayIabService(700): Creating IAB helper.
01-12 15:21:02.033: D/SOOMLA GoogleIabHelper(700): GoogleIabHelper helper created.
01-12 15:21:02.033: D/SOOMLA GooglePlayIabService(700): IAB helper Starting setup.
01-12 15:21:02.033: D/SOOMLA PurchaseObserver(700): Starting in-app billing setup.
01-12 15:21:02.053: E/NdkGlue(700): java.lang.IllegalStateException: java.lang.NullPointerException
01-12 15:21:02.053: E/NdkGlue(700): 	at com.soomla.cocos2dx.common.NdkGlue.dispatchNdkCall(NdkGlue.java:114)
01-12 15:21:02.053: E/NdkGlue(700): 	at com.soomla.cocos2dx.common.NdkGlue.receiveCppMessage(NdkGlue.java:74)
01-12 15:21:02.053: E/NdkGlue(700): 	at org.cocos2dx.lib.Cocos2dxRenderer.nativeInit(Native Method)
01-12 15:21:02.053: E/NdkGlue(700): 	at org.cocos2dx.lib.Cocos2dxRenderer.onSurfaceCreated(Cocos2dxRenderer.java:73)
01-12 15:21:02.053: E/NdkGlue(700): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1494)
01-12 15:21:02.053: E/NdkGlue(700): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
01-12 15:21:02.053: E/NdkGlue(700): Caused by: java.lang.NullPointerException
01-12 15:21:02.053: E/NdkGlue(700): 	at com.soomla.store.billing.google.GoogleIabHelper.startSetupInner(GoogleIabHelper.java:127)
01-12 15:21:02.053: E/NdkGlue(700): 	at com.soomla.store.billing.IabHelper.startSetup(IabHelper.java:75)
01-12 15:21:02.053: E/NdkGlue(700): 	at com.soomla.store.billing.google.GooglePlayIabService.startIabHelper(GooglePlayIabService.java:210)
01-12 15:21:02.053: E/NdkGlue(700): 	at com.soomla.store.billing.google.GooglePlayIabService.initializeBillingService(GooglePlayIabService.java:54)
01-12 15:21:02.053: E/NdkGlue(700): 	at com.soomla.store.SoomlaStore.restoreTransactions(SoomlaStore.java:175)
01-12 15:21:02.053: E/NdkGlue(700): 	at com.soomla.store.SoomlaStore.refreshInventory(SoomlaStore.java:312)
01-12 15:21:02.053: E/NdkGlue(700): 	at com.soomla.store.SoomlaStore.initialize(SoomlaStore.java:107)
01-12 15:21:02.053: E/NdkGlue(700): 	at com.soomla.cocos2dx.store.StoreService$2.handle(StoreService.java:90)
01-12 15:21:02.053: E/NdkGlue(700): 	at com.soomla.cocos2dx.common.NdkGlue.dispatchNdkCall(NdkGlue.java:104)
01-12 15:21:02.053: E/NdkGlue(700): 	... 5 more
01-12 15:21:02.053: E/NdkGlue(700): Unknown exception (java.lang.IllegalStateException: java.lang.NullPointerException)

Thanks.

**Comment by sluzky** [comment]
@MDKG is this the same as [this](http://answers.soom.la/t/resolved-soomla-crashing-in-cocos2d-x-on-android/906)?

**Comment by MDKG** [comment]
@sluzky Yes, it is.  You can close this now if you want.

**Comment by sluzky** [comment]
OK, thanks.
