### ISSUE TITLE
Getting error for architecture x86_64 

### ISSUE THREAD

**Issue by pavaniG** [soomla/cocos2dx-store#160]
Hi i am facing this Undefined symbols architecture issue. I am using Cocos2dx-v3.3.  Can you please help me with this? 
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ProfileService", referenced from:
      objc-class-ref in AppController.o
  "_OBJC_CLASS_$_ServiceManager", referenced from:
      objc-class-ref in AppController.o

Thank you
Pavani

**Comment by sluzky** [comment]
Hey @pavaniG,

- Are you using the profile module as well?
- Have you pulled the [soomla-cocos2dx-core](https://github.com/soomla/soomla-cocos2dx-core) module into your extensions folder?

**Comment by refaelos** [comment]
This issue is outdated. Closing. Open if relevant.
