### ISSUE TITLE
Cocos2d-JS in App Purchase V3

### ISSUE THREAD

**Issue by pisadam** [soomla/cocos2dx-store#162]
Will you support Cocos2d-JS V3?

**Comment by refaelos** [comment]
The master branch supports v3.3

**Comment by refaelos** [comment]
we're working on it

**Comment by vedi** [comment]
@pisadam, just found this old ticket... If it's still relevant for you, nowadays Soomla support Cocos2d-JS V3. The documentation is available here: https://github.com/soomla/cocos2dx-store/wiki/jsb3
