### ISSUE TITLE
Cannot initialize on iOS

### ISSUE THREAD

**Issue by haxpor** [soomla/cocos2dx-store#170]
I got this while trying to initialize.
Once I put the `soomla::CCSoomla::initialize` in a certain scene, and it didn't work. Next I thought I have to move it into the time when the app starts in AppDelegate. But it didn't work.

![screen shot 2015-05-18 at 1 37 44 am](https://cloud.githubusercontent.com/assets/673757/7671535/9f7ae97e-fcfe-11e4-8576-f5ed9a007725.png)

There's error in `soomla::CCCoreBridgeBinderIos::bind();`.

I'm running it on iOS 8.3, iPod touch gen 5 with cocos2dx 2.0.3.

**Comment by refaelos** [comment]
It would be best for you to ask this on http://answers.soom.la ... you'll get a faster answer.

**Comment by haxpor** [comment]
@refaelos Okay sure, I'll do it.
